-- SQL migration generated from prisma/schema.prisma (initial scaffolding)
-- Run this on your MySQL server (phpMyAdmin import or mysql CLI)

CREATE TABLE IF NOT EXISTS `Student` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `studentId` VARCHAR(100) DEFAULT NULL,
  `phone` VARCHAR(50) DEFAULT NULL,
  `avatar` TEXT DEFAULT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Teacher` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `phone` VARCHAR(50) DEFAULT NULL,
  `avatar` TEXT DEFAULT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `ClassLevel` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `section` VARCHAR(50) DEFAULT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Subject` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(100) DEFAULT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Indexes (if needed)
CREATE INDEX IF NOT EXISTS idx_student_school ON `Student` (`schoolId`);
CREATE INDEX IF NOT EXISTS idx_teacher_school ON `Teacher` (`schoolId`);
CREATE INDEX IF NOT EXISTS idx_class_school ON `ClassLevel` (`schoolId`);
CREATE INDEX IF NOT EXISTS idx_subject_school ON `Subject` (`schoolId`);

-- Exams table
CREATE TABLE IF NOT EXISTS `Exam` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `subject` VARCHAR(36) DEFAULT NULL,
  `passMark` INT DEFAULT NULL,
  `totalMark` INT DEFAULT NULL,
  `academicTerm` VARCHAR(36) DEFAULT NULL,
  `duration` INT DEFAULT NULL,
  `examDate` DATETIME DEFAULT NULL,
  `examTime` VARCHAR(50) DEFAULT NULL,
  `classLevel` VARCHAR(36) DEFAULT NULL,
  `questions` TEXT DEFAULT NULL,
  `createdBy` VARCHAR(36) DEFAULT NULL,
  `schoolId` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_exam_school ON `Exam` (`schoolId`);

-- Results table
CREATE TABLE IF NOT EXISTS `Result` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `studentId` VARCHAR(36) NOT NULL,
  `examId` VARCHAR(36) NOT NULL,
  `score` DOUBLE DEFAULT NULL,
  `grade` VARCHAR(50) DEFAULT NULL,
  `passMark` INT DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  `remarks` TEXT DEFAULT NULL,
  `answeredQuestions` TEXT DEFAULT NULL,
  `classLevel` VARCHAR(36) DEFAULT NULL,
  `academicTerm` VARCHAR(36) DEFAULT NULL,
  `academicYear` VARCHAR(36) DEFAULT NULL,
  `isPublished` TINYINT(1) DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_result_exam ON `Result` (`examId`);
